# Site settings
title: AIOps HOWTOs
email: dcacy@us.ibm.com
description: >
  Exercises to learn how to do some typical Cloud Pak for AIOps tasks.
lang: en-US

baseurl: "/aiops-howto" # the subpath of your site, e.g. /blog/
url: https://dcacy.github.io # the base hostname & protocol for your site
git_address: https://dcacy.github.io/aiops-howto.git
# git_edit_address: https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
# bootwatch: paper # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
# plugins:
#   - jekyll-feed
#   - jekyll-redirect-from
#   - jekyll-seo-tag
#   - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor
  - .history
timezone: America/Chicago
defaults:
# - scope:
#     path: _posts
#     type: posts
#   values:
#     layout: post
#     sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  # posts:
  #   permalink: /blog/:year/:month/:day/:title/
  #   output: true
